apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: web
          image: react-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
